# Generated by Django 2.1.7 on 2020-05-11 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0034_auto_20190705_1348'),
        ('ops', '0006_auto_20190318_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDeployExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('src_file_list', models.TextField()),
                ('dest', models.FilePathField(allow_folders=True, max_length=256, path='/', recursive=True)),
                ('mode', models.CharField(max_length=128, verbose_name='Mode')),
                ('group', models.CharField(max_length=128, verbose_name='Group')),
                ('_result', models.TextField(blank=True, null=True, verbose_name='Result')),
                ('is_finished', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('hosts', models.ManyToManyField(to='assets.Asset')),
                ('run_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SystemUser')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
