# Generated by Django 2.1.7 on 2020-05-15 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0034_auto_20190705_1348'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0008_auto_20200513_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDeployTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('src_file_list', models.TextField()),
                ('dest', models.CharField(max_length=256)),
                ('mode', models.CharField(max_length=8, verbose_name='Mode')),
                ('group', models.CharField(max_length=64, verbose_name='Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskArgument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('default_value', models.CharField(default='', max_length=256, verbose_name='Default Value')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('constraint_regex', models.CharField(max_length=128, verbose_name='Constraint Regex')),
                ('constraint_description', models.CharField(max_length=256, verbose_name='Constraint Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('_arguments_data', models.TextField(blank=True, null=True)),
                ('_result', models.TextField(blank=True, null=True, verbose_name='Result')),
                ('is_finished', models.BooleanField(default=False)),
                ('manual', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('execute_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('task_type', models.CharField(choices=[('file_deploy', '文件分发')], max_length=64)),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
                ('crontab', models.CharField(blank=True, help_text='5 * * * *', max_length=128, null=True, verbose_name='Crontab')),
                ('is_periodic', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='task_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.TaskMeta'),
        ),
        migrations.AddField(
            model_name='filedeploytask',
            name='arguments',
            field=models.ManyToManyField(to='ops.TaskArgument'),
        ),
        migrations.AddField(
            model_name='filedeploytask',
            name='hosts',
            field=models.ManyToManyField(to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='filedeploytask',
            name='last_modify_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filedeploytask',
            name='run_as',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SystemUser'),
        ),
        migrations.AddField(
            model_name='filedeploytask',
            name='task_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.TaskMeta'),
        ),
    ]
