# Generated by Django 2.1.7 on 2020-05-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_auto_20200519_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedeployexecution',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='filedeployexecution',
            name='run_as',
        ),
        migrations.RemoveField(
            model_name='filedeployexecution',
            name='user',
        ),
        migrations.DeleteModel(
            name='FileDeployExecution',
        ),
    ]
