# Generated by Django 2.1.7 on 2020-07-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_job_jobexecution_jobtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtask',
            name='failure_next_job_task_id',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='success_next_job_task_id',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
