# Generated by Django 2.1.7 on 2020-08-03 03:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_auto_20200717_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
                ('crontab', models.CharField(blank=True, help_text='5 * * * *', max_length=128, null=True, verbose_name='Crontab')),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('_arguments_data', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.Job')),
            ],
        ),
        migrations.CreateModel(
            name='CrontabTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
                ('crontab', models.CharField(blank=True, help_text='5 * * * *', max_length=128, null=True, verbose_name='Crontab')),
                ('enabled', models.BooleanField(default=True)),
                ('_arguments_data', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('task_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.TaskMeta')),
            ],
        ),
    ]
