# Generated by Django 2.1.7 on 2020-08-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0014_crontabjob_crontabtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmeta',
            name='crontab',
        ),
        migrations.RemoveField(
            model_name='taskmeta',
            name='is_periodic',
        ),
    ]
