# Generated by Django 2.1.7 on 2020-08-07 08:40

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0015_auto_20200804_1516'),
        ('users', '0022_auto_20190625_1105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perms', '0007_remove_assetpermission_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPermission',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('jobs', models.ManyToManyField(blank=True, to='ops.Job', verbose_name='Job')),
                ('tasks', models.ManyToManyField(blank=True, to='ops.TaskMeta', verbose_name='Task')),
                ('user_groups', models.ManyToManyField(blank=True, to='users.UserGroup', verbose_name='User group')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
