# Generated by Django 2.1.7 on 2019-12-02 10:43

import didicloud.models.dc2
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0034_auto_20190705_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dc2',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(default='dc2', max_length=128, verbose_name='AssetType')),
                ('instance_id', models.CharField(max_length=128, verbose_name='InstanceId')),
                ('inner_ip', models.CharField(db_index=True, max_length=128, verbose_name='InnerIp')),
                ('public_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='PublicIp')),
                ('instance_name', models.CharField(max_length=128, verbose_name='InstanceName')),
                ('region', models.CharField(max_length=128, verbose_name='RegionId')),
                ('status', models.CharField(max_length=128, verbose_name='Status')),
                ('nodes', models.ManyToManyField(default=didicloud.models.dc2.default_node, related_name='dc2', to='assets.Node', verbose_name='Nodes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
