# Generated by Django 2.1.7 on 2019-06-27 06:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecs',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=128, verbose_name='InstanceId')),
                ('inner_ip', models.CharField(db_index=True, max_length=128, verbose_name='InnerIp')),
                ('public_ip', models.CharField(max_length=128, verbose_name='PublicIp')),
                ('network_type', models.CharField(max_length=128, verbose_name='NetworkType')),
                ('instance_name', models.CharField(max_length=128, verbose_name='InstanceName')),
                ('region', models.CharField(max_length=128, verbose_name='RegionId')),
                ('status', models.CharField(max_length=128, verbose_name='Status')),
                ('io_optimized', models.BooleanField(verbose_name='IoOptimized')),
                ('expired_time', models.DateTimeField(verbose_name='ExpiredTime')),
                ('maximum_bandwidth', models.IntegerField(default=0, verbose_name='InternetMaxBandwidthOut')),
                ('cpu', models.IntegerField(default=0, verbose_name='Cpu')),
                ('memeory', models.IntegerField(default=0, verbose_name='Memory')),
                ('instance_charge_type', models.CharField(max_length=128, verbose_name='InstanceChargeType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
