# Generated by Django 2.1.7 on 2019-06-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alicloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecs',
            old_name='memeory',
            new_name='memory',
        ),
    ]
