# Generated by Django 2.1.7 on 2019-07-03 02:36

import alicloud.models.kvstore
import alicloud.models.oss
import alicloud.models.rds
import alicloud.models.slb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_auto_20190521_1703'),
        ('alicloud', '0005_ecs_instance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvStore',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=128, verbose_name='InstanceId')),
                ('connection_domain', models.CharField(blank=True, max_length=128, null=True, verbose_name='ConnectionDomain')),
                ('network_type', models.CharField(max_length=128, verbose_name='NetworkType')),
                ('instance_name', models.CharField(max_length=128, verbose_name='InstanceName')),
                ('region', models.CharField(max_length=128, verbose_name='RegionId')),
                ('status', models.CharField(max_length=128, verbose_name='Status')),
                ('expired_time', models.DateTimeField(verbose_name='ExpiredTime')),
                ('engine_version', models.CharField(max_length=128, verbose_name='EngineVersion')),
                ('instance_class', models.CharField(max_length=128, verbose_name='InstanceClass')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('qps', models.IntegerField(verbose_name='QPS')),
                ('bandwidth', models.IntegerField(verbose_name='Bandwidth')),
                ('connections', models.IntegerField(verbose_name='Connections')),
                ('nodes', models.ManyToManyField(default=alicloud.models.kvstore.default_node, related_name='kvstore', to='assets.Node', verbose_name='Nodes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Oss',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=128, verbose_name='InstanceId')),
                ('extranet_endpoint', models.CharField(blank=True, max_length=128, null=True, verbose_name='ConnectionDomain')),
                ('intranet_endpoint', models.CharField(max_length=128, verbose_name='NetworkType')),
                ('instance_name', models.CharField(max_length=128, verbose_name='InstanceName')),
                ('region', models.CharField(max_length=128, verbose_name='RegionId')),
                ('status', models.CharField(max_length=128, verbose_name='Status')),
                ('create_time', models.DateTimeField(verbose_name='CreateTime')),
                ('nodes', models.ManyToManyField(default=alicloud.models.oss.default_node, related_name='oss', to='assets.Node', verbose_name='Nodes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rds',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=128, verbose_name='InstanceId')),
                ('network_type', models.CharField(max_length=128, verbose_name='NetworkType')),
                ('instance_name', models.CharField(max_length=128, verbose_name='InstanceName')),
                ('region', models.CharField(max_length=128, verbose_name='RegionId')),
                ('status', models.CharField(max_length=128, verbose_name='Status')),
                ('expired_time', models.DateTimeField(verbose_name='ExpiredTime')),
                ('engine_version', models.CharField(max_length=128, verbose_name='EngineVersion')),
                ('connection_string', models.CharField(max_length=128, verbose_name='ConnectionString')),
                ('connections', models.IntegerField(verbose_name='MaxConnections')),
                ('memory', models.IntegerField(verbose_name='DBInstanceMemory')),
                ('iops', models.IntegerField(verbose_name='MaxIOPS')),
                ('storage', models.IntegerField(verbose_name='DBInstanceStorage')),
                ('nodes', models.ManyToManyField(default=alicloud.models.rds.default_node, related_name='rds', to='assets.Node', verbose_name='Nodes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slb',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=128, verbose_name='InstanceId')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='PublicIp')),
                ('network_type', models.CharField(max_length=128, verbose_name='NetworkType')),
                ('instance_name', models.CharField(max_length=128, verbose_name='InstanceName')),
                ('region', models.CharField(max_length=128, verbose_name='RegionId')),
                ('status', models.CharField(max_length=128, verbose_name='Status')),
                ('create_time', models.DateTimeField(verbose_name='CreateTime')),
                ('address_type', models.CharField(max_length=128, verbose_name='AddressType')),
                ('address_ip_version', models.CharField(max_length=128, verbose_name='AddressIPVersion')),
                ('nodes', models.ManyToManyField(default=alicloud.models.slb.default_node, related_name='slb', to='assets.Node', verbose_name='Nodes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
