# Generated by Django 2.1.7 on 2019-07-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alicloud', '0006_kvstore_oss_rds_slb'),
    ]

    operations = [
        migrations.AddField(
            model_name='rds',
            name='cpu',
            field=models.IntegerField(default=0, verbose_name='DBInstanceCPU'),
        ),
    ]
