# Generated by Django 2.1.7 on 2019-07-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alicloud', '0007_rds_cpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rds',
            name='expired_time',
            field=models.DateTimeField(null=True, verbose_name='ExpiredTime'),
        ),
    ]
