# Generated by Django 2.1.7 on 2019-07-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alicloud', '0008_auto_20190703_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(verbose_name='OrderId')),
                ('order_id_index', models.BigIntegerField(default=0, verbose_name='OrderIdIndex')),
                ('product_code', models.CharField(max_length=20, verbose_name='ProductCode')),
                ('payment_status', models.CharField(max_length=20, verbose_name='PaymentStatus')),
                ('order_type', models.CharField(max_length=20, verbose_name='OrderType')),
                ('payment_time', models.DateTimeField(verbose_name='PaymentTime')),
                ('create_time', models.DateTimeField(verbose_name='CreateTime')),
                ('payment_amount', models.FloatField(default=0.0, verbose_name='PaymentAmount')),
                ('payment_gross_amount', models.FloatField(default=0.0, verbose_name='PaymentGrossAmount')),
                ('instance_ids', models.TextField(verbose_name='InstanceIDs')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('order_id', 'order_id_index')},
        ),
    ]
