# Generated by Django 2.1.7 on 2019-07-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alicloud', '0009_auto_20190705_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecs',
            name='type',
            field=models.CharField(default='ecs', max_length=128, verbose_name='AssetType'),
        ),
        migrations.AddField(
            model_name='kvstore',
            name='type',
            field=models.CharField(default='kvstore', max_length=128, verbose_name='AssetType'),
        ),
        migrations.AddField(
            model_name='oss',
            name='type',
            field=models.CharField(default='oss', max_length=128, verbose_name='AssetType'),
        ),
        migrations.AddField(
            model_name='rds',
            name='type',
            field=models.CharField(default='rds', max_length=128, verbose_name='AssetType'),
        ),
        migrations.AddField(
            model_name='slb',
            name='type',
            field=models.CharField(default='slb', max_length=128, verbose_name='AssetType'),
        ),
    ]
