# Generated by Django 2.1.7 on 2019-08-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alicloud', '0011_auto_20190715_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='cycle',
            field=models.CharField(default='', max_length=50, verbose_name='BillingCycle'),
        ),
        migrations.AddField(
            model_name='billing',
            name='instance_id',
            field=models.CharField(default='', max_length=128, verbose_name='InstanceId'),
        ),
        migrations.AddField(
            model_name='billing',
            name='product_name',
            field=models.CharField(default='', max_length=200, verbose_name='ProductName'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='billing',
            name='product_code',
            field=models.CharField(default='', max_length=20, verbose_name='ProductCode'),
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('cycle', 'product_code', 'instance_id')},
        ),
        migrations.AlterModelTable(
            name='billing',
            table='alicloud_billing',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='instance_ids',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='order_id_index',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='payment_gross_amount',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='payment_time',
        ),
    ]
