# Generated by Django 2.1.7 on 2019-08-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alicloud', '0012_auto_20190731_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('node_id', models.UUIDField()),
                ('type', models.CharField(max_length=128, verbose_name='AssetType')),
                ('instance_id', models.CharField(max_length=128, verbose_name='InstanceId')),
                ('instance_name', models.CharField(max_length=128, verbose_name='InstanceName')),
                ('status', models.CharField(max_length=128, verbose_name='Status')),
            ],
            options={
                'db_table': 'alicloud_assets',
                'managed': False,
            },
        ),
    ]
