# Generated by Django 2.1.7 on 2020-01-06 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alicloud', '0014_auto_20191226_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosTemplate',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('body', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
