# Generated by Django 2.1.7 on 2020-01-13 07:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alicloud', '0015_rostemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackCreateRecord',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('params', models.TextField()),
                ('uid', models.CharField(max_length=256)),
                ('results', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
