# Generated by Django 2.1.7 on 2020-02-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alicloud', '0016_stackcreaterecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecs',
            name='zone',
            field=models.CharField(default='', max_length=128, verbose_name='ZoneId'),
        ),
    ]
